import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <nav
          style={{
            backgroundColor: "skyBlue",
            display: "flex",
            justifyContent: "center",
            alignItems: "center",
            fontSize: "20px",
            gap: "10px",
            flexDirection: "column",
          }}
        >
          <Link href="/"><button>Home</button></Link>
          <Link href="/art"><button>Art</button></Link>
          <Link href="/posts"><button>Posts</button></Link>
          <Link href="/posts/posts2"><button>posts2</button></Link>
          <Link href="/art/art2"><button>art2</button></Link>
          <Link href="/art/art2/mona-lisa"><button>mona-lisa</button></Link>
          <Link href="/art/art2/starry-galaxy"><button>starry-galaxy</button></Link>
          <Link href="/art/art2/sunset"><button>sunset</button></Link>
          <Link href="/compns"><button>todo</button></Link>
        </nav>

        {children}
      </body>
    </html>
  );
}
